services:
  backend-dotnet:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    container_name: backend-dotnet
    ports:
      - "12000:12000"
    networks:
      - app-network
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:12000

  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    container_name: backend-java
    ports:
      - "12000:12000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
