#!/bin/sh
FRONTEND_DIR="frontend"
BACKEND_DIR="backend"

if [ -d "$FRONTEND_DIR" ]; then
 echo "Frontend directory found. Running lint..."
 cd "$FRONTEND_DIR" || exit 1
 yarn prettier
 LINT_EXIT_CODE=$?

 if [ $LINT_EXIT_CODE -ne 0 ]; then
 echo "Frontend linting failed. Aborting commit."
 cd - || exit 1
 exit 1
 fi

 echo "Frontend linting completed. Adding changes..."
 git add .
 cd ..
else
 echo "Frontend directory not found. Skipping lint."
fi

if [ -d "$BACKEND_DIR" ]; then
 echo "Backend directory found. Running lint..."
 cd "$BACKEND_DIR" || exit 1
 ./gradlew spotlessApply
 SPOTLESS_EXIT_CODE=$?

 if [ $SPOTLESS_EXIT_CODE -ne 0 ]; then
 echo "Backend linting failed. Aborting commit."
 cd - || exit 1
 exit 1
 fi

 echo "Backend linting completed. Adding changes..."
 git add .
 cd ..
else
 echo "Backend directory not found. Skipping lint."
fi

exit 0
